set(_CATKIN_CURRENT_PACKAGE "ssf_updates")
set(ssf_updates_VERSION "0.1.0")
set(ssf_updates_MAINTAINER "Stephan Weiss <none@none.com>, Markus Achtelik <none@none.com>")
set(ssf_updates_PACKAGE_FORMAT "1")
set(ssf_updates_BUILD_DEPENDS "roscpp" "ssf_core" "geometry_msgs")
set(ssf_updates_BUILD_EXPORT_DEPENDS "roscpp" "ssf_core" "geometry_msgs")
set(ssf_updates_BUILDTOOL_DEPENDS "catkin")
set(ssf_updates_BUILDTOOL_EXPORT_DEPENDS )
set(ssf_updates_EXEC_DEPENDS "roscpp" "ssf_core" "geometry_msgs")
set(ssf_updates_RUN_DEPENDS "roscpp" "ssf_core" "geometry_msgs")
set(ssf_updates_TEST_DEPENDS )
set(ssf_updates_DOC_DEPENDS )
set(ssf_updates_DEPRECATED "")